sudo: false
dist: trusty

language: node_js
node_js:
  - "6"
  - "7"
  - "node"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update      

install:
  - npm install


after_install:
  - echo "echoing in after_install steps"
  # - npm rebuild node-sass
  # - ./node_modules/protractor/bin/webdriver-manager update

before_script:
  - npm rebuild node-sass
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run test

after_success:
  - "BRANCHES_TO_MERGE_REGEX='^' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=a ./merge.sh"
env:
  global:
  - secure: cjSbs+51rGnIQeUV/2ekYdZ3uC+k25i5gQittuULyzJrgXMMmBl1p0T1bbC6f2xVBjKmPb09iO7jRK9wAKheD2DXI+boOXk6kppUrVRsKLGqUMVCweAa9wsdi4u8JoW9mGqJCypl0y5T/b7iJYGvHCJLadsET9mvyYCNHM63GRM=
  - secure: R3O/O5BskbWFSqSN9G1x1EDo83MHiyLue0GVMf5cCV+eiJHkag0A7cxYVGpoWzTx+t1UArMIpGLSzuIMiBpnLsR0vjm3R8UWhYM1ruqJCqdDP1bmJ7uYKGlJau2xHG86fc+190ChSY1l5ipjyui60564Yp02scePbX1aXbQXGbY=


after_failure:
    - echo "echoing in after_failure steps"

after_script:
- test $TRAVIS_PULL_REQUEST = false \
  && echo "not a pull request" \
  && git push \

before_deploy:
- test $TRAVIS_TEST_RESULT = 0 \# check that build passed successfully
  && cd $TRAVIS_BUILD_DIR \
  && tar -zcvf amber-storm-$TRAVIS_BRANCH.tar.gz dist

deploy:
  provider: releases
  api_key:
    secure: securekeyhere
  file: myrepo-$TRAVIS_BRANCH.tar.gz
  skip_cleanup: true
  on:
    condition: $PRODBUILDCOMPLETE = true    
    all_branches: true
    tags: true

# after_deploy:
#   - ssh git@mysite.biz "./deploy.sh $TRAVIS_BRANCH"      